<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AP.Data\AP.Data.csproj" />
    <ProjectReference Include="..\AP.ServiceLocator\AP.ServiceLocator.csproj" />
    <ProjectReference Include="..\Mcv.Service\Mcv.Service.csproj" />
  </ItemGroup>

</Project>
